using System.Diagnostics;

namespace Prompt2Plot.Contracts;

/// <summary>
/// Base implementation of <see cref="IChartType"/> used to describe
/// visualization formats supported by the prompt pipeline.
/// </summary>
/// <remarks>
/// This class provides a standardized way to describe chart structures for the LLM.
/// Derived chart types define:
///
/// <list type="bullet">
/// <item><description><see cref="Name"/> — chart type identifier</description></item>
/// <item><description><see cref="Fields"/> — expected dataset field structure</description></item>
/// <item><description><see cref="SpecificTool"/> — optional visualization tool restriction</description></item>
/// <item><description><see cref="AdditionalInfo"/> — extra guidance for the model</description></item>
/// </list>
///
/// The description generated by <see cref="ToPromptString"/> is embedded
/// into the prompt during prompt construction so the model understands
/// how SQL query results must be structured.
///
/// Implementations should only contain metadata and must remain deterministic.
/// </remarks>
[DebuggerDisplay("{ToPromptString()}")]
public abstract class ChartTypeBase : IChartType
{
	/// <inheritdoc/>
	public abstract string Name { get; }

	/// <summary>
	/// Gets the dataset fields required by this chart type.
	/// </summary>
	/// <remarks>
	/// The key represents the expected field name and the value describes
	/// the expected data type or semantic meaning.
	/// </remarks>
	public abstract Dictionary<string, string>[] Fields { get; }

	/// <summary>
	/// Gets optional additional instructions describing how the chart fields
	/// should be interpreted.
	/// </summary>
	public virtual string? AdditionalInfo => null;

	/// <inheritdoc/>
	public string ToPromptString()
	{
		var fieldsPart = string.Join(
			" or ",
			Fields.Select(fieldsOption =>
				"[" + string.Join(
					", ",
					fieldsOption.Select(f =>
						$"{f.Key}: {f.Value}")) + "]"));

		var additionalPart = AdditionalInfo != null ? $": {AdditionalInfo}" : string.Empty;

		return $"'{Name}' with fields {fieldsPart}{additionalPart}";
	}
}
