using Microsoft.Extensions.Logging;

namespace Prompt2Plot.ClickHouse.Logging;

internal static partial class QueryValidationLogs
{
	[LoggerMessage(
		EventId = 10,
		Level = LogLevel.Debug,
		Message =
			"Validating ClickHouse SQL queries generated by the model. QueryCount: {QueryCount}. WorkItemId: {WorkItemId}.")]
	public static partial void ValidationStarted(ILogger logger, int queryCount, ulong workItemId);

	[LoggerMessage(
		EventId = 11,
		Level = LogLevel.Debug,
		Message = "ClickHouse SQL query validated successfully. WorkItemId: {WorkItemId}.")]
	public static partial void QueryValidated(ILogger logger, ulong workItemId);

	[LoggerMessage(
		EventId = 12,
		Level = LogLevel.Warning,
		Message = "ClickHouse query validation failed. WorkItemId: {WorkItemId}.")]
	public static partial void QueryValidationFailed(ILogger logger, ulong workItemId, Exception exception);

	[LoggerMessage(
		EventId = 13,
		Level = LogLevel.Warning,
		Message = "Datasets missing in model response. WorkItemId: {WorkItemId}.")]
	public static partial void DatasetsMissingInResponse(ILogger logger, ulong workItemId);

	[LoggerMessage(
		EventId = 14,
		Level = LogLevel.Warning,
		Message = "Model response contains datasets with empty SQL queries. WorkItemId: {WorkItemId}.")]
	public static partial void EmptyQueryDetected(ILogger logger, ulong workItemId);

	[LoggerMessage(
		EventId = 13,
		Level = LogLevel.Warning,
		Message = "No datasets provided in model response. WorkItemId: {WorkItemId}.")]
	public static partial void DatasetsEmptyInResponse(ILogger logger, ulong workItemId);
}
