using ClickHouse.Driver;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Prompt2Plot.ClickHouse.Logging;

namespace Prompt2Plot.ClickHouse;

/// <summary>
/// A validation pipeline stage that verifies SQL queries generated by the model
/// against a ClickHouse database.
/// </summary>
/// <remarks>
/// This stage performs lightweight validation of model-generated SQL queries
/// before they are executed as part of dataset retrieval.
///
/// Validation is performed by executing <c>EXPLAIN PLAN</c> for each query.
/// This ensures that:
///
/// <list type="bullet">
/// <item><description>The SQL syntax is valid</description></item>
/// <item><description>Referenced tables and columns exist</description></item>
/// <item><description>The query can be successfully planned by ClickHouse</description></item>
/// <item><description>
/// The query is a <c>SELECT</c>-type query. Non-read queries such as
/// <c>INSERT</c>, <c>ALTER</c>, or <c>DROP</c> will fail validation because
/// they cannot be used with <c>EXPLAIN PLAN</c>.
/// </description></item>
/// </list>
///
/// If validation fails:
///
/// <list type="bullet">
/// <item><description>The work item is marked for retry</description></item>
/// <item><description>An auxiliary prompt containing the database error is added</description></item>
/// </list>
///
/// The auxiliary prompt allows the language model to repair the query during
/// the next execution attempt.
/// </remarks>
public sealed class ClickHouseQueryValidationStage : IValidationPipelineStage
{
	private readonly string _connectionString;
	private readonly IHttpClientFactory _httpClientFactory;
	private readonly string _httpClientName;

	private readonly ILogger _logger;

	public ClickHouseQueryValidationStage(
		ClickHouseQueryValidationStageSettings settings,
		ILoggerFactory? loggerFactory = null)
	{
		ArgumentNullException.ThrowIfNull(settings);
		ArgumentNullException.ThrowIfNull(settings.ConnectionSettings);
		ArgumentException.ThrowIfNullOrWhiteSpace(settings.ConnectionSettings.ConnectionString);
		ArgumentNullException.ThrowIfNull(settings.ConnectionSettings.HttpClientFactory);
		ArgumentException.ThrowIfNullOrWhiteSpace(settings.ConnectionSettings.ConnectionString);

		_connectionString = settings.ConnectionSettings.ConnectionString;
		_httpClientFactory = settings.ConnectionSettings.HttpClientFactory;
		_httpClientName = settings.ConnectionSettings.HttpClientName;

		var logFactory = loggerFactory ?? NullLoggerFactory.Instance;
		_logger = logFactory.CreateLogger<ClickHouseQueryValidationStage>();
	}

	public async Task ExecuteAsync(ValidationContext context, CancellationToken cancellationToken)
	{
		if (context.ModelResponse.Datasets == null)
		{
			QueryValidationLogs.DatasetsMissingInResponse(_logger, context.WorkItemId);

			context.Errors.Add("Failed to parse model response datasets.");
			context.MarkForRetry();

			return;
		}

		if (!context.ModelResponse.Datasets.Any())
		{
			QueryValidationLogs.DatasetsMissingInResponse(_logger, context.WorkItemId);

			return;
		}

		foreach (var dataset in context.ModelResponse.Datasets)
		{
			if (dataset.SqlQuery != null)
			{
				dataset.SqlQuery = dataset.SqlQuery.Trim().TrimEnd(';');
			}
		}

		var queries = context.ModelResponse.Datasets!.Select(d => d.SqlQuery).ToList();

		if (queries.Any(query => query == null))
		{
			QueryValidationLogs.EmptyQueryDetected(_logger, context.WorkItemId);

			context.Errors.Add("Model response contains datasets with empty SQL queries.");
			context.MarkForRetry();

			return;
		}

		QueryValidationLogs.ValidationStarted(_logger, queries.Count, context.WorkItemId);

		using var clickHouseConnection = new ClickHouseClient(
			_connectionString,
			_httpClientFactory,
			_httpClientName);

		foreach (var query in queries)
		{
			try
			{
				await clickHouseConnection.ExecuteReaderAsync(
					$"explain plan {query}",
					cancellationToken: cancellationToken);

				QueryValidationLogs.QueryValidated(_logger, context.WorkItemId);
			}
			catch (ClickHouseServerException clickHouseException)
			{
				QueryValidationLogs.QueryValidationFailed(_logger, context.WorkItemId, clickHouseException);

				context.Errors.Add("ClickHouse query validation failed.");
				context.MarkForRetry();

				context.RetryAuxiliaryPrompts.Add(string.Format(AuxiliaryPrompt, query, clickHouseException.Message));
			}
			catch (Exception exception)
			{
				QueryValidationLogs.QueryValidationFailed(_logger, context.WorkItemId, exception);

				context.Errors.Add(exception.Message);
			}
		}
	}

	private const string AuxiliaryPrompt = """
		Previously, the following ClickHouse SQL query produced an error during validation.

		Query:
		{0}

		ClickHouse error:
		{1}
		""";
}
